resources:
- deployment.yaml
- service.yaml
namespace: easysoftware
apiVersion: kustomize.config.k8s.io/v1beta1
commonAnnotations:
  kubernetes.ops.cluster: shanghai-icsl-cluster
  kubernetes.ops.email: ""
  kubernetes.ops.os.base: debian
  kubernetes.ops.owner: wucaiping
  kubernetes.ops.region: shanghai
kind: Kustomization
